In [1]:
#Basic Python
s = "Hi there vishal!"

In [2]:
s.split(' ')

['Hi', 'there', 'vishal!']

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
"The diameter of {0} is {1} kilometers".format(planet,diameter)


'The diameter of Earth is 12742 kilometers'

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [8]:
#Numpy
import numpy as np

In [9]:
np.zeros((10),int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [12]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

In [13]:
np.arange(0,9,1).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [15]:
#Pandas
import pandas as pd

In [16]:
pd.DataFrame(index=range(3),columns=range(2))

0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN

In [17]:
pd.Series(pd.date_range('1/1/2023','2/10/2023'))

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-11
11   2023-01-12
12   2023-01-13
13   2023-01-14
14   2023-01-15
15   2023-01-16
16   2023-01-17
17   2023-01-18
18   2023-01-19
19   2023-01-20
20   2023-01-21
21   2023-01-22
22   2023-01-23
23   2023-01-24
24   2023-01-25
25   2023-01-26
26   2023-01-27
27   2023-01-28
28   2023-01-29
29   2023-01-30
30   2023-01-31
31   2023-02-01
32   2023-02-02
33   2023-02-03
34   2023-02-04
35   2023-02-05
36   2023-02-06
37   2023-02-07
38   2023-02-08
39   2023-02-09
40   2023-02-10
dtype: datetime64[ns]

In [20]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24